name: Refresh data

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    
jobs:
  refresh-data:
    name: Refresh data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch data
        id: fetch-data
        run: |
          curl -X POST -d "@query.txt" -o data.json https://overpass-api.de/api/interpreter
      - name: Add and commit OSM data
        uses: EndBug/add-and-commit@2d7c2e89fcb436f8e139cc80813bd030bdd40c4b
        with:
          default_author: github_actions
          message: 'Refresh data'
          add: data.json
